development:
  adapter: postgresql
  encoding: unicode
  database: kindly_development
  pool: 5
  username: kindly
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kindly_test
  pool: 5
  username: kindly
  password:

